### ISSUE TITLE
Problems with a9s MongoDB for PCF doc

### ISSUE THREAD

**Issue by jncd** [pivotal-cf/docs-a9s-mongodb#12]
Hello @lucaspinto
The release notes are updated to v1.0.1 with a new date. But, the front page (Product Snapshot) is stale with the old date and v1.0.0.  I'll make the change for you — it should publish within 24 hours, but you should check the text too.
Also, I noticed that the Release Notes have "Upcoming" — I'll delete that; we've been warned about legal issues wrt to promising something is coming.

**Comment by lucaspinto** [comment]
@jncd thank you for that.
